log_level: INFO

service:
  host: "0.0.0.0"
  http_port: 6333
  grpc_port: 6334

storage:
  storage_path: "/qdrant/storage/data"
  snapshots_path: "/qdrant/storage/snapshots"
  on_disk_payload: false

optimizers:
  max_segment_size: 10000
  flush_interval_sec: 5
  max_optimization_threads: 2
