services:
  ml_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_api
    restart: unless-stopped
    env_file:
      - .env
    networks: [ proxy, monitor, databases ]
    ports:
      - "8000:8000"
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ml_api.rule=Host(`api.mathislambert.fr`)"
      - "traefik.http.routers.ml_api.entrypoints=websecure"
      - "traefik.http.routers.ml_api.tls=true"
      - "traefik.http.routers.ml_api.tls.certresolver=letsencrypt"
      - "traefik.http.services.ml_api.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  monitor:
    external: true
  databases:
    external: true
